### ISSUE TITLE
关于jekyll和git pages的基础功能问题

### ISSUE THREAD

**Issue by scottming** [scottming/scottming.github.io#1]
这里怎么添加图片呢？要把图片先上传到微博，然后地址弄过来嘛？

**Comment by ghost** [comment]
对，写文章和之前用hexo一样的，就是markdown的图片语法，微博图床，七牛都行

**Comment by ghost** [comment]
测试 @ 通知功能 @scottming

**Comment by scottming** [comment]
![导航实现](http://7xjuve.com1.z0.glb.clouddn.com/屏幕快照%202015-08-22%20下午10.20.34.png)这个是怎么实现的，在markdown里面有简单点的语法吗?貌似掌心用的不是markdown语法，![导航语法](http://7xjuve.com1.z0.glb.clouddn.com/导航语法.png)

**Comment by scottming** [comment]
![看不到自己](http://7xjuve.com1.z0.glb.clouddn.com/看不到自己%202015-08-22%20下午10.37.13.png)这里看不到自己的回复

**Comment by ghost** [comment]
文章里面插入下面两行就有目录了
- TOC
  {:toc}

**Comment by scottming** [comment]
插入之后的确有目录了，不过显示的是无序列表。http://scottming.github.io/2013/11/23/change.html
目录的有序列表和无序列表分别是怎么实现的呢？http://scottming.github.io/2012/12/22/111test.html

**Comment by ghost** [comment]
那个*换成1试试看

这个目录生成靠的是kramdown引擎

**Comment by scottming** [comment]
关于博客下的那条线的调整：css文件里面找到这块 去掉border-top那行（by ibrother ）.![图](http://7xjuve.com1.z0.glb.clouddn.com/关于博客名称弟下的线.jpg)

**Comment by scottming** [comment]
导航改成
1 TOC
{:toc}
后变成下图的效果![q](http://7xjuve.com1.z0.glb.clouddn.com/关于导航语法问题.png)@ibrother

**Comment by scottming** [comment]
除了不加“##”外，还有别的办法可以使“文章目录”不进入“目录”里吗？
![文章目录](http://7xjuve.com1.z0.glb.clouddn.com/文章目录.png)

**Comment by ghost** [comment]
@scottming 明兄看pull, 然后合并吧

**Comment by ghost** [comment]
不想放到目录的标题前面加上 {:.no_toc} 试试

**Comment by scottming** [comment]
这个没有效果![效果](http://7xjuve.com1.z0.glb.clouddn.com/文章目录没效果.png)
另外罗兄说得pull是什么？这个吗？没看到啊 ![mei](http://7xjuve.com1.z0.glb.clouddn.com/没pull.png)

**Comment by scottming** [comment]
另外版权名称怎么修改呢？![板权](http://7xjuve.com1.z0.glb.clouddn.com/2013-08-23版权名称的修改.png)@ibrother

**Comment by ghost** [comment]
{:no_toc} 难道是因为多了一个点

右上角的小蓝点可以看到 pull 通知, 直接合并就可以

版权在这里改 https://github.com/scottming/scottming.github.io/edit/master/_layouts/post.html

**Comment by scottming** [comment]
罗兄，还是不行，{:no_toc} 
https://github.com/scottming/scottming.github.io/blob/master/_posts/2015-08-23-studygit.md

**Comment by ghost** [comment]
哈哈,原来是用错位置了

放到不显示目录标题的下面
{:.no_toc}

用有点的

**Comment by scottming** [comment]
另外我应该如何对我的文章进行分类呢，看到目录好像只有年份的分类。希望能按照标签来分类，如：随笔、技术、vc、创业等。

**Comment by ghost** [comment]
添加伪页面实现需求,具体的我时间贴代码,明兄稍作修改即可

**Comment by scottming** [comment]
那太感谢罗兄了。

**Comment by ghost** [comment]
哈哈, 没事的

**Comment by scottming** [comment]
@ibrother 罗兄，今天一休应该会拉你进python群，你注意下。

**Comment by ghost** [comment]
@scottming 好的，麻烦明兄了

scottming notifications@github.com于2015年9月26日周六 09:55写道：
